package com.amazon.payments.lpa.response.autogenerated.model;

import com.amazon.payments.lpa.response.autogenerated.model.Address;
import com.amazon.payments.lpa.response.autogenerated.model.IdList;
import com.amazon.payments.lpa.response.autogenerated.model.OrderItemCategories;
import com.amazon.payments.lpa.response.autogenerated.model.Status;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuthorizationDetails", propOrder = {
    "amazonAuthorizationId",
    "authorizationReferenceId",
    "authorizationBillingAddress",
    "sellerAuthorizationNote",
    "authorizationAmount",
    "capturedAmount",
    "authorizationFee",
    "idList",
    "creationTimestamp",
    "expirationTimestamp",
    "authorizationStatus",
    "orderItemCategories",
    "captureNow",
    "softDescriptor",
    "addressVerificationCode"
})
public class AuthorizationDetails {

    @XmlElement(name = "AmazonAuthorizationId", required = true)
    protected String amazonAuthorizationId;
    @XmlElement(name = "AuthorizationReferenceId", required = true)
    protected String authorizationReferenceId;
    @XmlElement(name = "AuthorizationBillingAddress")
    protected Address authorizationBillingAddress;
    @XmlElement(name = "SellerAuthorizationNote", required = true)
    protected String sellerAuthorizationNote;
    @XmlElement(name = "AuthorizationAmount", required = true)
    protected Price authorizationAmount;
    @XmlElement(name = "CapturedAmount", required = true)
    protected Price capturedAmount;
    @XmlElement(name = "AuthorizationFee", required = true)
    protected Price authorizationFee;
    @XmlElement(name = "IdList", required = true)
    protected IdList idList;
    @XmlElement(name = "CreationTimestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationTimestamp;
    @XmlElement(name = "ExpirationTimestamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expirationTimestamp;
    @XmlElement(name = "AuthorizationStatus", required = true)
    protected Status authorizationStatus;
    @XmlElement(name = "OrderItemCategories", required = true)
    protected OrderItemCategories orderItemCategories;
    @XmlElement(name = "CaptureNow")
    protected boolean captureNow;
    @XmlElement(name = "SoftDescriptor", required = true)
    protected String softDescriptor;
    @XmlElement(name = "AddressVerificationCode")
    protected String addressVerificationCode;
    
    public AuthorizationDetails() {
        super();
    }

    public String getAmazonAuthorizationId() {
        return amazonAuthorizationId;
    }

    public String getAuthorizationReferenceId() {
        return authorizationReferenceId;
    }

    public Address getAuthorizationBillingAddress() {
        return authorizationBillingAddress;
    }

    public String getSellerAuthorizationNote() {
        return sellerAuthorizationNote;
    }

    public Price getAuthorizationAmount() {
        return authorizationAmount;
    }

    public Price getCapturedAmount() {
        return capturedAmount;
    }

    public Price getAuthorizationFee() {
        return authorizationFee;
    }


    public IdList getIdList() {
        return idList;
    }

    public XMLGregorianCalendar getCreationTimestamp() {
        return creationTimestamp;
    }

    public XMLGregorianCalendar getExpirationTimestamp() {
        return expirationTimestamp;
    }

    public Status getAuthorizationStatus() {
        return authorizationStatus;
    }

    public OrderItemCategories getOrderItemCategories() {
        return orderItemCategories;
    }

    public boolean isCaptureNow() {
        return captureNow;
    }

    public String getSoftDescriptor() {
        return softDescriptor;
    }

    public String getAddressVerificationCode() {
        return addressVerificationCode;
    }
}
