
package com.amazon.payments.lpa.response.autogenerated.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillingAgreementDetails", propOrder = {
    "amazonBillingAgreementId",
    "billingAgreementLimits",
    "buyer",
    "sellerNote",
    "platformId",
    "destination",
    "billingAddress",
    "releaseEnvironment",
    "sellerBillingAgreementAttributes",
    "billingAgreementStatus",
    "constraints",
    "creationTimestamp",
    "expirationTimestamp",
    "billingAgreementConsent",
    "orderLanguage"
})
public class BillingAgreementDetails {

    @XmlElement(name = "AmazonBillingAgreementId", required = true)
    protected String amazonBillingAgreementId;
    @XmlElement(name = "BillingAgreementLimits")
    protected BillingAgreementLimits billingAgreementLimits;
    @XmlElement(name = "Buyer", required = true)
    protected Buyer buyer;
    @XmlElement(name = "SellerNote")
    protected String sellerNote;
    @XmlElement(name = "PlatformId")
    protected String platformId;
    @XmlElement(name = "Destination")
    protected Destination destination;
    @XmlElement(name = "BillingAddress")
    protected BillingAddress billingAddress;
    @XmlElement(name = "ReleaseEnvironment", required = true)
    protected ReleaseEnvironment releaseEnvironment;
    @XmlElement(name = "SellerBillingAgreementAttributes")
    protected SellerBillingAgreementAttributes sellerBillingAgreementAttributes;
    @XmlElement(name = "BillingAgreementStatus", required = true)
    protected BillingAgreementStatus billingAgreementStatus;
    @XmlElement(name = "Constraints")
    protected Constraints constraints;
    @XmlElement(name = "CreationTimestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationTimestamp;
    @XmlElement(name = "ExpirationTimestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expirationTimestamp;
    @XmlElement(name = "BillingAgreementConsent")
    protected Boolean billingAgreementConsent;
    @XmlElement(name = "OrderLanguage")
    protected String orderLanguage;
    

    public BillingAgreementDetails() {
        super();
    }


    public String getAmazonBillingAgreementId() {
        return amazonBillingAgreementId;
    }


    public BillingAgreementLimits getBillingAgreementLimits() {
        return billingAgreementLimits;
    }

    public Buyer getBuyer() {
        return buyer;
    }

    public String getSellerNote() {
        return sellerNote;
    }

    public String getPlatformId() {
        return platformId;
    }


    public Destination getDestination() {
        return destination;
    }

    public BillingAddress getBillingAddress() {
        return billingAddress;
    }

    public ReleaseEnvironment getReleaseEnvironment() {
        return releaseEnvironment;
    }

    public SellerBillingAgreementAttributes getSellerBillingAgreementAttributes() {
        return sellerBillingAgreementAttributes;
    }

    public BillingAgreementStatus getBillingAgreementStatus() {
        return billingAgreementStatus;
    }


    public Constraints getConstraints() {
        return constraints;
    }


    public XMLGregorianCalendar getCreationTimestamp() {
        return creationTimestamp;
    }

    public XMLGregorianCalendar getExpirationTimestamp() {
        return expirationTimestamp;
    }

    public Boolean isBillingAgreementConsent() {
        return billingAgreementConsent;
    }

    public String getOrderLanguage() {
        return orderLanguage;
    }


}