package com.amazon.payments.lpa.response.autogenerated.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillingAgreementLimits", propOrder = {
    "amountLimitPerTimePeriod",
    "timePeriodStartDate",
    "timePeriodEndDate",
    "currentRemainingBalance"
})
public class BillingAgreementLimits {

    @XmlElement(name = "AmountLimitPerTimePeriod")
    protected Price amountLimitPerTimePeriod;
    @XmlElement(name = "TimePeriodStartDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timePeriodStartDate;
    @XmlElement(name = "TimePeriodEndDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timePeriodEndDate;
    @XmlElement(name = "CurrentRemainingBalance")
    protected Price currentRemainingBalance;


    public BillingAgreementLimits() {
        super();
    }


    public Price getAmountLimitPerTimePeriod() {
        return amountLimitPerTimePeriod;
    }


    public XMLGregorianCalendar getTimePeriodStartDate() {
        return timePeriodStartDate;
    }

    public XMLGregorianCalendar getTimePeriodEndDate() {
        return timePeriodEndDate;
    }

    public Price getCurrentRemainingBalance() {
        return currentRemainingBalance;
    }


}
