package com.amazon.payments.lpa.response.autogenerated.model;



import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillingAddress", propOrder = {
    "addressType",
    "physicalAddress"
})
public class BillingAddress {

    @XmlElement(name = "AddressType")
    protected String addressType;
    @XmlElement(name = "PhysicalAddress")
    protected Address physicalAddress;

    public BillingAddress() {
        super();
    }


    public String getAddressType() {
        return addressType;
    }

    public void setAddressType(String value) {
        this.addressType = value;
    }

    public boolean isSetAddressType() {
        return (this.addressType!= null);
    }

    public Address getPhysicalAddress() {
        return physicalAddress;
    }

    public void setPhysicalAddress(Address value) {
        this.physicalAddress = value;
    }

    public boolean isSetPhysicalAddress() {
        return (this.physicalAddress!= null);
    }


    public BillingAddress withAddressType(String value) {
        setAddressType(value);
        return this;
    }

    public BillingAddress withPhysicalAddress(Address value) {
        setPhysicalAddress(value);
        return this;
    }


}