package com.amazon.payments.lpa.response.autogenerated.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "CancelOrderReferenceResult")
public class CancelOrderReferenceResult {

    public CancelOrderReferenceResult() {
        super();
    }



}
