package com.amazon.payments.lpa.response.autogenerated.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Constraint", propOrder = {
    "constraintID",
    "description"
})
public class Constraint {

    @XmlElement(name = "ConstraintID")
    protected String constraintID;
    @XmlElement(name = "Description")
    protected String description;

    public Constraint() {
        super();
    }

    public String getConstraintID() {
        return constraintID;
    }

    public String getDescription() {
        return description;
    }


}
