package com.amazon.payments.lpa.response.autogenerated.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Destination", propOrder = {
    "destinationType",
    "physicalDestination"
})
public class Destination {

    @XmlElement(name = "DestinationType")
    protected String destinationType;
    @XmlElement(name = "PhysicalDestination")
    protected Address physicalDestination;

    public Destination() {
        super();
    }

    public String getDestinationType() {
        return destinationType;
    }

    public Address getPhysicalDestination() {
        return physicalDestination;
    }

}
