package com.amazon.payments.lpa.response.autogenerated.model;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.parser.Parser;

public class HttpResponseObject {
    private int statusCode;
    private String responseXml;
    
    public HttpResponseObject(int responseCode , String rawXmlString) {
        this.statusCode = responseCode;
        this.responseXml = rawXmlString;
    }
    
    public int getStatusCode() {
        return this.statusCode;
    }
    
    public String getData() {
        return this.responseXml;
    }
    
    public Document toDocument() {
         return Jsoup.parse(this.responseXml, "", Parser.xmlParser());
    }
}
