package com.amazon.payments.lpa.response.autogenerated.model;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderReferenceAttributes", propOrder = {
    "orderTotal",
    "platformId",
    "sellerNote",
    "sellerOrderAttributes"
})
public class OrderReferenceAttributes {

    @XmlElement(name = "OrderTotal", required = true)
    protected OrderTotal orderTotal;
    
    @XmlElement(name = "PlatformId")
    protected String platformId;

    @XmlElement(name = "SellerNote")
    protected String sellerNote;
    
    @XmlElement(name = "SellerOrderAttributes")
    protected SellerOrderAttributes sellerOrderAttributes;

    public OrderReferenceAttributes() {
        super();
    }

    public OrderTotal getOrderTotal() {
        return orderTotal;
    }

    public String getPlatformId() {
        return platformId;
    }


    public String getSellerNote() {
        return sellerNote;
    }

    public SellerOrderAttributes getSellerOrderAttributes() {
        return sellerOrderAttributes;
    }


 
}
