package com.amazon.payments.lpa.response.autogenerated.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderTotal", propOrder = {
    "currencyCode",
    "amount"
})
public class OrderTotal {

    @XmlElement(name = "CurrencyCode")
    protected String currencyCode;
    @XmlElement(name = "Amount")
    protected String amount;

    public OrderTotal() {
        super();
    }

    public String getCurrencyCode() {
        return currencyCode;
    }

    public String getAmount() {
        return amount;
    }


}
