package com.amazon.payments.lpa.response.autogenerated.model;

import com.amazon.payments.lpa.response.autogenerated.model.BillingAddress;
import com.amazon.payments.lpa.response.autogenerated.model.Buyer;
import com.amazon.payments.lpa.response.autogenerated.model.Constraints;
import com.amazon.payments.lpa.response.autogenerated.model.Destination;
import com.amazon.payments.lpa.response.autogenerated.model.IdList;
import com.amazon.payments.lpa.response.autogenerated.model.OrderReferenceStatus;
import com.amazon.payments.lpa.response.autogenerated.model.OrderTotal;
import com.amazon.payments.lpa.response.autogenerated.model.ParentDetails;
import com.amazon.payments.lpa.response.autogenerated.model.SellerOrderAttributes;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderReferenceDetails", propOrder = {
    "amazonOrderReferenceId",
    "buyer",
    "orderTotal",
    "sellerNote",
    "platformId",
    "destination",
    "billingAddress",
    "releaseEnvironment",
    "sellerOrderAttributes",
    "orderReferenceStatus",
    "constraints",
    "creationTimestamp",
    "expirationTimestamp",
    "parentDetails",
    "idList",
    "orderLanguage"
})
public class OrderReferenceDetails {

    @XmlElement(name = "AmazonOrderReferenceId", required = true)
    protected String amazonOrderReferenceId;
    @XmlElement(name = "Buyer", required = true)
    protected Buyer buyer;
    @XmlElement(name = "OrderTotal")
    protected OrderTotal orderTotal;
    @XmlElement(name = "SellerNote")
    protected String sellerNote;
    @XmlElement(name = "PlatformId")
    protected String platformId;
    @XmlElement(name = "Destination")
    protected Destination destination;
    @XmlElement(name = "BillingAddress")
    protected BillingAddress billingAddress;
    @XmlElement(name = "ReleaseEnvironment", required = true)
    protected ReleaseEnvironment releaseEnvironment;
    @XmlElement(name = "SellerOrderAttributes")
    protected SellerOrderAttributes sellerOrderAttributes;
    @XmlElement(name = "OrderReferenceStatus", required = true)
    protected OrderReferenceStatus orderReferenceStatus;
    @XmlElement(name = "Constraints")
    protected Constraints constraints;
    @XmlElement(name = "CreationTimestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationTimestamp;
    @XmlElement(name = "ExpirationTimestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expirationTimestamp;
    @XmlElement(name = "ParentDetails")
    protected ParentDetails parentDetails;
    @XmlElement(name = "IdList")
    protected IdList idList;
    @XmlElement(name = "OrderLanguage")
    protected String orderLanguage;

    
    public OrderReferenceDetails() {
        super();
    }

    public String getAmazonOrderReferenceId() {
        return amazonOrderReferenceId;
    }

    public Buyer getBuyer() {
        return buyer;
    }

    public OrderTotal getOrderTotal() {
        return orderTotal;
    }

    public String getSellerNote() {
        return sellerNote;
    }

    public String getPlatformId() {
        return platformId;
    }

    public Destination getDestination() {
        return destination;
    }

    public BillingAddress getBillingAddress() {
        return billingAddress;
    }

    public ReleaseEnvironment getReleaseEnvironment() {
        return releaseEnvironment;
    }

    public SellerOrderAttributes getSellerOrderAttributes() {
        return sellerOrderAttributes;
    }
    
    public OrderReferenceStatus getOrderReferenceStatus() {
        return orderReferenceStatus;
    }

    public Constraints getConstraints() {
        return constraints;
    }

    public XMLGregorianCalendar getCreationTimestamp() {
        return creationTimestamp;
    }

    public XMLGregorianCalendar getExpirationTimestamp() {
        return expirationTimestamp;
    }

    public ParentDetails getParentDetails() {
        return parentDetails;
    }

    public IdList getIdList() {
        return idList;
    }

    public String getOrderLanguage() {
        return orderLanguage;
    }

}
