package com.amazon.payments.lpa.response.autogenerated.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Price", propOrder = {
    "amount",
    "currencyCode"
})
public class Price {

    @XmlElement(name = "Amount", required = true)
    protected String amount;
    @XmlElement(name = "CurrencyCode", required = true)
    protected String currencyCode;

    public Price() {
        super();
    }

    public String getAmount() {
        return amount;
    }


    public String getCurrencyCode() {
        return currencyCode;
    }


}
