package com.amazon.payments.lpa.response.autogenerated.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RefundDetails", propOrder = {
    "amazonRefundId",
    "refundReferenceId",
    "sellerRefundNote",
    "refundType",
    "refundAmount",
    "feeRefunded",
    "creationTimestamp",
    "refundStatus",
    "softDescriptor",
    "providerCreditReversalSummaryList"
})
public class RefundDetails {

    @XmlElement(name = "AmazonRefundId", required = true)
    protected String amazonRefundId;
    @XmlElement(name = "RefundReferenceId", required = true)
    protected String refundReferenceId;
    @XmlElement(name = "SellerRefundNote", required = true)
    protected String sellerRefundNote;
    @XmlElement(name = "RefundType", required = true)
    protected RefundType refundType;
    @XmlElement(name = "RefundAmount", required = true)
    protected Price refundAmount;
    @XmlElement(name = "FeeRefunded", required = true)
    protected Price feeRefunded;
    @XmlElement(name = "CreationTimestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationTimestamp;
    @XmlElement(name = "RefundStatus", required = true)
    protected Status refundStatus;
    @XmlElement(name = "SoftDescriptor", required = true)
    protected String softDescriptor;
    @XmlElement(name = "ProviderCreditReversalSummaryList")
    protected ProviderCreditReversalSummaryList providerCreditReversalSummaryList;

    /**
     * Default constructor
     * 
     */
    public RefundDetails() {
        super();
    }


    public String getAmazonRefundId() {
        return amazonRefundId;
    }


    public String getRefundReferenceId() {
        return refundReferenceId;
    }

    public String getSellerRefundNote() {
        return sellerRefundNote;
    }


    public RefundType getRefundType() {
        return refundType;
    }

    public Price getRefundAmount() {
        return refundAmount;
    }

    public Price getFeeRefunded() {
        return feeRefunded;
    }

    public XMLGregorianCalendar getCreationTimestamp() {
        return creationTimestamp;
    }

    public Status getRefundStatus() {
        return refundStatus;
    }

    public String getSoftDescriptor() {
        return softDescriptor;
    }


    public ProviderCreditReversalSummaryList getProviderCreditReversalSummaryList() {
        return providerCreditReversalSummaryList;
    }

}
