package com.amazon.payments.lpa.response.autogenerated.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


@XmlType(name = "ReleaseEnvironment")
@XmlEnum
public enum ReleaseEnvironment {

    @XmlEnumValue("Live")
    LIVE("Live"),
    @XmlEnumValue("Sandbox")
    SANDBOX("Sandbox");
    private final String value;

    ReleaseEnvironment(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return value();
    }

    public static ReleaseEnvironment fromValue(String v) {
        for (ReleaseEnvironment c: ReleaseEnvironment.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
