package com.amazon.payments.paywithamazon.request;

import java.io.Serializable;

/**
 * Container for the parameters to the {@link com.amazon.payments.lpa.Client#closeAuthorization(CloseAuthorizationRequest) closeAuthorization operation}.
 * For more information documentation, see  
 * <a href="https://payments.amazon.com/documentation/"> API Reference</a>
 */
public class CloseAuthorizationRequest implements Serializable{
        
    //required parameters
    private String amazonAuthorizationId;
    
    //optional parameters
    private String closureReason;
    private String mwsAuthToken; 
    
    /**
     * 
     * @param amazonAuthorizationId 
     *              The authorization identifier that was generated by Amazon 
     *              in the earlier call to Authorize.
     * 
     */
    public CloseAuthorizationRequest(String amazonAuthorizationId) {
        this.amazonAuthorizationId = amazonAuthorizationId;
    }
    
    /**
     * 
     * @param closureReason
     *                  A description for the closure that is displayed in emails to the customer.
     */
    public CloseAuthorizationRequest setClosureReason(String closureReason) {
        this.closureReason = closureReason;
        return this;
    }

    /**
     * Applicable for third-party solution providers only. 
     * 
     * @param mwsAuthToken 
     */
    public CloseAuthorizationRequest setMWSAuthToken(String mwsAuthToken) {
        this.mwsAuthToken = mwsAuthToken;
        return this;
    }

    /**
     * The authorization identifier that was generated by Amazon 
     *              in the earlier call to Authorize.
     * 
     * @return AmazonAuthorizationId specified in request
     */
    public String getAmazonAuthorizationId() {
        return amazonAuthorizationId;
    }
    
    /**
     *  A description for the closure that is displayed in emails to the customer.
     * 
     * @return ClosureReason specified in request
     */
    public String getClosureReason() {
        return closureReason;
    }

    /**
     * Applicable for third-party solution providers only. 
     * 
     * @return MWSAuthToken specified in request
     */
    public String getMwsAuthToken() {
        return mwsAuthToken;
    }

    /**
     * Returns a string representation of this object; useful for testing and
     * debugging.
     *
     * @return A string representation of this object.
     *
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "CloseAuthorizationRequest{" + "amazonAuthorizationId=" + amazonAuthorizationId + ", closureReason=" + closureReason + ", mwsAuthToken=" 
                + mwsAuthToken + '}';
    }


}
