package com.amazon.payments.paywithamazon.request;

import java.io.Serializable;

/**
 * Container for the parameters to the {@link com.amazon.payments.lpa.Client#captureDetails(GetCaptureDetailsRequest) GetCaptureDetails operation}.
 * For more information documentation, see  
 * <a href="https://payments.amazon.com/documentation/"> API Reference</a>
 */
public class GetCaptureDetailsRequest implements Serializable{
        
    private String amazonCaptureId;
    private String mwsAuthToken;   
    
    /**
    * @param amazonCaptureId The capture identifier that was generated by Amazon 
    *                        on the earlier call to Capture.
    */
    public GetCaptureDetailsRequest(String amazonCaptureId) {
        this.amazonCaptureId = amazonCaptureId;
    }
    
     /**
     * Set the value of mwsAuthToken
     *
     * @param mwsAuthToken new value of mwsAuthToken
     */
    public GetCaptureDetailsRequest setMWSAuthToken(String mwsAuthToken) {
        this.mwsAuthToken = mwsAuthToken;
        return this;
    }
    
    /**
     * Get the value of AmazonCaptureId
     *
     * @param amazonCaptureId 
     */
    public String getAmazonCaptureId() {
        return amazonCaptureId;
    }

    /**
     * Get the value of mwsAuthToken
     *
     * @param mwsAuthToken 
     */
    public String getMwsAuthToken() {
        return mwsAuthToken;
    }

    /**
     * Returns a string representation of this object; useful for testing and
     * debugging.
     *
     * @return A string representation of this object.
     *
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "GetCaptureDetailsRequest{" + "amazonCaptureId=" + amazonCaptureId + ", mwsAuthToken=" + mwsAuthToken + '}';
    }
    
}
