package com.amazon.payments.lpa.test;

import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;
import com.amazon.payments.lpa.response.parser.GetOrderReferenceDetailsResponseData;
import com.amazon.payments.lpa.response.parser.GetProviderCreditDetailsResponseData;
import com.amazon.payments.lpa.response.parser.Parser;
import org.junit.Assert;
import org.junit.Test;

public class ResponseObjectUnitTests {
   @Test
    public void testGetOrderReferenceDetailsResponse() throws Exception{
        String rawResponse = TestConstants.GetOrderReferenceDetailsResponse;
        HttpResponseObject response = new HttpResponseObject(200, rawResponse);
        GetOrderReferenceDetailsResponseData res = Parser.getOrderReferenceDetails(response);
        Assert.assertEquals(res.getDetails().getAmazonOrderReferenceId() , "P01-1234567-1234567");     
        Assert.assertEquals(res.getDetails().getOrderReferenceStatus().getState() , "Draft");
        Assert.assertEquals(res.getDetails().getDestination().getDestinationType() , "Physical");
        Assert.assertEquals(res.getRequestId() , "5f20169b-7ab2-11df-bcef-d35615e2b044");
        Assert.assertEquals(res.getDetails().getReleaseEnvironment().value(), "Live");
        Assert.assertEquals(res.getDetails().getDestination().getPhysicalDestination().getCountryCode(), "US");
        Assert.assertEquals(res.getDetails().getDestination().getPhysicalDestination().getCity(), "New York");
        Assert.assertEquals(res.getDetails().getDestination().getPhysicalDestination().getPostalCode(), "10101-9876");
        Assert.assertEquals(res.getDetails().getDestination().getPhysicalDestination().getStateOrRegion(), "NY");
        Assert.assertEquals(res.toXML() , rawResponse);
    }
    
    @Test
    public void testGetProviderCreditDetailsResponse() throws Exception {
        String rawResponse = TestConstants.GetProviderCreditDetailsResponse;
        HttpResponseObject response = new HttpResponseObject(200, rawResponse);
        GetProviderCreditDetailsResponseData res = Parser.getGetProviderCreditDetails(response);
        Assert.assertEquals(res.getDetails().getAmazonProviderCreditId() , "S01-2117025-2155793-P045170");     
        Assert.assertEquals(res.getDetails().getCreditAmount().getAmount() , "1.00");
        Assert.assertEquals(res.getDetails().getCreditAmount().getCurrencyCode() , "USD");
        Assert.assertEquals(res.getRequestId() , "21162350-7135-46ae-aa20-68d5361cef17");
        Assert.assertEquals(res.toXML() , rawResponse);
    }
}
