package com.amazon.payments.lpa.exceptions;

import com.amazon.payments.lpa.response.autogenerated.model.ErrorResponse;
import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;
import javax.xml.bind.JAXBException;

public class AmazonServiceException extends Exception {
    
    private String message;
    private int statusCode;
    private String errorCode;
    private String errorType;
    private String requestId;
    private String response;
    
    public AmazonServiceException(ErrorResponse errorResponse , HttpResponseObject response) {
        super(errorResponse.getError().get(0).getMessage() + response.getData());
        this.response = response.getData();
        this.statusCode = response.getStatusCode();
        this.message = errorResponse.getError().get(0).getMessage();
        this.errorCode = errorResponse.getError().get(0).getCode();
        this.errorType = errorResponse.getError().get(0).getType();
    }
    
    public AmazonServiceException(HttpResponseObject response , JAXBException exception) {
        super("Encountered exception while parsing XML: "+response.getData() , exception);
        this.response = response.getData();
        this.statusCode = response.getStatusCode();
    }
    
    public AmazonServiceException(String message , Throwable t) {
        super(message , t);
        this.message = message;
    }
    
    public AmazonServiceException(String message) {
        super(message);
    }

    public int getStatusCode() {
        return statusCode;
    }

    public String getErrorCode() {
        return errorCode;
    }

    public String getErrorType() {
        return errorType;
    }

    public String getRequestId() {
        return requestId;
    }

    public String getXml() {
        return response;
    }
    
    
}
