package com.amazon.payments.paywithamazon.response.autogenerated.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * Represents the total amount that you can charge a buyer in a given time period.
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillingAgreementLimits", propOrder = {
    "amountLimitPerTimePeriod",
    "timePeriodStartDate",
    "timePeriodEndDate",
    "currentRemainingBalance"
})
public class BillingAgreementLimits {

    @XmlElement(name = "AmountLimitPerTimePeriod")
    protected Price amountLimitPerTimePeriod;
    @XmlElement(name = "TimePeriodStartDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timePeriodStartDate;
    @XmlElement(name = "TimePeriodEndDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timePeriodEndDate;
    @XmlElement(name = "CurrentRemainingBalance")
    protected Price currentRemainingBalance;


    public BillingAgreementLimits() {
        super();
    }


    /**
     * The maximum amount that can be charged on a billing agreement in the 
     * time period defined by TimePeriodStartDate and TimePeriodEndDate.
     * Type: Price
     * 
     * @return amountLimitPerTimePeriod
     */
    public Price getAmountLimitPerTimePeriod() {
        return amountLimitPerTimePeriod;
    }


    /**
     * The start date of the period during which the AmountLimitPerTimePeriod applies.
     * 
     * @return timePeriodStartDate
     */
    public XMLGregorianCalendar getTimePeriodStartDate() {
        return timePeriodStartDate;
    }

    /**
     * The end date of the period during which the AmountLimitPerTimePeriod applies.
     * 
     * @return timePeriodEndDate
     */
    public XMLGregorianCalendar getTimePeriodEndDate() {
        return timePeriodEndDate;
    }

    /**
     * The remaining balance that can be charged in the current time period. Type: Price
     * 
     * @return currentRemainingBalance
     */
    public Price getCurrentRemainingBalance() {
        return currentRemainingBalance;
    }


}
