@javax.xml.bind.annotation.XmlSchema(namespace = "http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.amazon.payments.paywithamazon.response.autogenerated.model;
