package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.response.autogenerated.model.CancelOrderReferenceResponse;
import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;

public class CancelOrderReferenceResponseData {
    
    private String responseXML;
    private String requestId;
    
    public CancelOrderReferenceResponseData(CancelOrderReferenceResponse cancelOrderReferenceResponse , HttpResponseObject rawResponse) {
        this.responseXML = rawResponse.getData();
        if(cancelOrderReferenceResponse != null) {
            if(cancelOrderReferenceResponse.getResponseMetadata() != null) {
                this.requestId = cancelOrderReferenceResponse.getResponseMetadata().getRequestId();
            }
        }
    }

    public String getResponseXML() {
        return responseXML;
    }

    public String getRequestId() {
        return requestId;
    }
    
}
