package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.response.autogenerated.model.CaptureDetails;
import com.amazon.payments.lpa.response.autogenerated.model.CaptureResponse;
import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;

public class CaptureResponseData {
    
    private String rawXML;
    private String requestId;
    private CaptureDetails captureDetails;
    
    public CaptureResponseData(CaptureResponse captureResponse , HttpResponseObject rawResponse) {
        this.rawXML = rawResponse.getData();
        if(captureResponse != null) {
            if(captureResponse.getCaptureResult() != null) {
                captureDetails = captureResponse.getCaptureResult().getCaptureDetails();
            }
            this.requestId = captureResponse.getResponseMetadata().getRequestId();
        }
    }

    public String toXML() {
        return rawXML;
    }

    public String getRequestId() {
        return requestId;
    }

    public CaptureDetails getDetails() {
        return captureDetails;
    }

}
