package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.response.autogenerated.model.CloseAuthorizationResponse;
import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;

public class CloseAuthorizationResponseData {
    private String responseXML;
    private String requestId;
    
    public CloseAuthorizationResponseData(CloseAuthorizationResponse closeAuthorizationResponse , HttpResponseObject rawResponse) {
        this.responseXML = rawResponse.getData();
        if(closeAuthorizationResponse != null) {
            if(closeAuthorizationResponse.getResponseMetadata() != null) {
                this.requestId = closeAuthorizationResponse.getResponseMetadata().getRequestId();
            }
        }
    }

    public String toXML() {
        return responseXML;
    }

    public String getRequestId() {
        return requestId;
    }
}
