package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.response.autogenerated.model.CloseBillingAgreementResponse;
import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;

public class CloseBillingAgreementResponseData {
    
    private String responseXML;
    private String requestId;
    
    public CloseBillingAgreementResponseData(CloseBillingAgreementResponse closeBillingAgreementResponse , HttpResponseObject rawResponse) {
        this.responseXML = rawResponse.getData();
        if(closeBillingAgreementResponse != null) {
            if(closeBillingAgreementResponse.getResponseMetadata() != null) {
                this.requestId = closeBillingAgreementResponse.getResponseMetadata().getRequestId();
            }
        }
    }

    public String toXML() {
        return responseXML;
    }

    public String getRequestId() {
        return requestId;
    }
    
}
