package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.response.autogenerated.model.CloseOrderReferenceResponse;
import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;

public class CloseOrderReferenceResponseData {
    
    private String responseXML;
    private String requestId;
    
    public CloseOrderReferenceResponseData(CloseOrderReferenceResponse closeOrderReferenceResponse , HttpResponseObject rawResponse) {
        this.responseXML = rawResponse.getData();
        if(closeOrderReferenceResponse != null) {
            if(closeOrderReferenceResponse.getResponseMetadata() != null) {
                this.requestId = closeOrderReferenceResponse.getResponseMetadata().getRequestId();
            }
        }
    }

    public String toXML() {
        return responseXML;
    }

    public String getRequestId() {
        return requestId;
    }
    
}
