package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.response.autogenerated.model.ConfirmBillingAgreementResponse;
import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;

public class ConfirmBillingAgreementResponseData {
    
    private String responseXML;
    private String requestId;
    
    public ConfirmBillingAgreementResponseData(ConfirmBillingAgreementResponse confirmBillingAgreementResponse , HttpResponseObject rawResponse) {
        this.responseXML = rawResponse.getData();
        if(confirmBillingAgreementResponse != null) {
            if(confirmBillingAgreementResponse.getResponseMetadata() != null) {
                this.requestId = confirmBillingAgreementResponse.getResponseMetadata().getRequestId();
            }
        }
    }

    public String toXML() {
        return responseXML;
    }

    public String getRequestId() {
        return requestId;
    }
    
}
