package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.response.autogenerated.model.ConfirmOrderReferenceResponse;
import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;

public class ConfirmOrderReferenceResponseData {
    
    private String responseXML;
    private String requestId;
    
    public ConfirmOrderReferenceResponseData(ConfirmOrderReferenceResponse confirmOrderReferenceResponse , HttpResponseObject rawResponse) {
        this.responseXML = rawResponse.getData();
        if(confirmOrderReferenceResponse != null) {
            if(confirmOrderReferenceResponse.getResponseMetadata() != null) {
                this.requestId = confirmOrderReferenceResponse.getResponseMetadata().getRequestId();
            }
        }
    }

    public String toXML() {
        return responseXML;
    }

    public String getRequestId() {
        return requestId;
    }
    
}
