package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.response.autogenerated.model.AuthorizationDetails;
import com.amazon.payments.lpa.response.autogenerated.model.GetAuthorizationDetailsResponse;
import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;

public class GetAuthorizationDetailsResponseData {
    
    private String rawXML;
    private String requestId;
    private AuthorizationDetails authorizationDetails;
    
    public GetAuthorizationDetailsResponseData(GetAuthorizationDetailsResponse authorizeResponse , HttpResponseObject rawResponse) {
        this.rawXML = rawResponse.getData();
        if(authorizeResponse != null) {
            if(authorizeResponse.getGetAuthorizationDetailsResult() != null) {
                authorizationDetails = authorizeResponse.getGetAuthorizationDetailsResult().getAuthorizationDetails();
            }
            this.requestId = authorizeResponse.getResponseMetadata().getRequestId();
        }
    }

    public String toXML() {
        return rawXML;
    }

    public String getRequestId() {
        return requestId;
    }

    public AuthorizationDetails getDetails() {
        return authorizationDetails;
    }

}
