package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.response.autogenerated.model.CaptureDetails;
import com.amazon.payments.lpa.response.autogenerated.model.GetCaptureDetailsResponse;
import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;

public class GetCaptureDetailsResponseData {
    
    private String rawXML;
    private String requestId;
    private CaptureDetails captureDetails;
    
    public GetCaptureDetailsResponseData(GetCaptureDetailsResponse getCaptureDetailsResponse , HttpResponseObject rawResponse) {
        this.rawXML = rawResponse.getData();
        if(getCaptureDetailsResponse != null) {
            if(getCaptureDetailsResponse.getGetCaptureDetailsResult() != null) {
                captureDetails = getCaptureDetailsResponse.getGetCaptureDetailsResult().getCaptureDetails();
            }
            this.requestId = getCaptureDetailsResponse.getResponseMetadata().getRequestId();
        }
    }

    public String toXML() {
        return rawXML;
    }

    public String getRequestId() {
        return requestId;
    }

    public CaptureDetails getDetails() {
        return captureDetails;
    }

}
