package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.response.autogenerated.model.GetOrderReferenceDetailsResponse;
import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;
import com.amazon.payments.lpa.response.autogenerated.model.OrderReferenceDetails;


public class GetOrderReferenceDetailsResponseData {
    
    private String rawXML;
    private String requestId;
    private OrderReferenceDetails orderReferenceDetails;
    
    public GetOrderReferenceDetailsResponseData(GetOrderReferenceDetailsResponse response , HttpResponseObject rawResponse) {
        this.rawXML = rawResponse.getData();
        if(response != null) {
            this.requestId = response.getResponseMetadata().getRequestId();
            if(response.getGetOrderReferenceDetailsResult() != null) { 
               orderReferenceDetails = response.getGetOrderReferenceDetailsResult().getOrderReferenceDetails();
            }
        }
    }

    public String toXML() {
        return rawXML;
    }

    public String getRequestId() {
        return requestId;
    }

    public OrderReferenceDetails getDetails() {
        return orderReferenceDetails;
    }
    
    
    

}
