package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.response.autogenerated.model.GetRefundDetailsResponse;
import com.amazon.payments.lpa.response.autogenerated.model.RefundDetails;
import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;

public class GetRefundDetailsResponseData {
    
    private String rawXML;
    private String requestId;
    private RefundDetails refundDetails;
    
    public GetRefundDetailsResponseData(GetRefundDetailsResponse getRefundDetailsResponse , HttpResponseObject rawResponse) {
        this.rawXML = rawResponse.getData();
        if(getRefundDetailsResponse != null) {
            if(getRefundDetailsResponse.getGetRefundDetailsResult() != null) {
                refundDetails = getRefundDetailsResponse.getGetRefundDetailsResult().getRefundDetails();
            }
            this.requestId = getRefundDetailsResponse.getResponseMetadata().getRequestId();
        }
    }

    public String toXML() {
        return rawXML;
    }

    public String getRequestId() {
        return requestId;
    }

    public RefundDetails getDetails() {
        return refundDetails;
    }

}
