package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.exceptions.AmazonClientException;
import com.amazon.payments.lpa.exceptions.AmazonServiceException;
import com.amazon.payments.lpa.response.autogenerated.model.AuthorizeOnBillingAgreementResponse;
import com.amazon.payments.lpa.response.autogenerated.model.AuthorizeResponse;
import com.amazon.payments.lpa.response.autogenerated.model.CancelOrderReferenceResponse;
import com.amazon.payments.lpa.response.autogenerated.model.CaptureResponse;
import com.amazon.payments.lpa.response.autogenerated.model.CloseAuthorizationResponse;
import com.amazon.payments.lpa.response.autogenerated.model.CloseBillingAgreementResponse;
import com.amazon.payments.lpa.response.autogenerated.model.CloseOrderReferenceResponse;
import com.amazon.payments.lpa.response.autogenerated.model.ConfirmBillingAgreementResponse;
import com.amazon.payments.lpa.response.autogenerated.model.ConfirmOrderReferenceResponse;
import com.amazon.payments.lpa.response.autogenerated.model.ErrorResponse;
import com.amazon.payments.lpa.response.autogenerated.model.GetAuthorizationDetailsResponse;
import com.amazon.payments.lpa.response.autogenerated.model.GetBillingAgreementDetailsResponse;
import com.amazon.payments.lpa.response.autogenerated.model.GetCaptureDetailsResponse;
import com.amazon.payments.lpa.response.autogenerated.model.GetOrderReferenceDetailsResponse;
import com.amazon.payments.lpa.response.autogenerated.model.GetProviderCreditDetailsResponse;
import com.amazon.payments.lpa.response.autogenerated.model.GetProviderCreditReversalDetailsResponse;
import com.amazon.payments.lpa.response.autogenerated.model.GetRefundDetailsResponse;
import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;
import com.amazon.payments.lpa.response.autogenerated.model.RefundResponse;
import com.amazon.payments.lpa.response.autogenerated.model.ReverseProviderCreditResponse;
import com.amazon.payments.lpa.response.autogenerated.model.SetBillingAgreementDetailsResponse;
import com.amazon.payments.lpa.response.autogenerated.model.SetOrderReferenceDetailsResponse;
import com.amazon.payments.lpa.response.autogenerated.model.ValidateBillingAgreementResponse;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;

public class Parser {
    
    public static GetOrderReferenceDetailsResponseData getOrderReferenceDetails(HttpResponseObject rawResponse) throws Exception {
        GetOrderReferenceDetailsResponse response = marshalXML(GetOrderReferenceDetailsResponse.class , rawResponse);
        return new GetOrderReferenceDetailsResponseData(response, rawResponse);    
    }
    
    public static SetOrderReferenceDetailsResponseData setOrderReferenceDetails(HttpResponseObject rawResponse) throws Exception {
        SetOrderReferenceDetailsResponse response = marshalXML(SetOrderReferenceDetailsResponse.class , rawResponse);
        return new SetOrderReferenceDetailsResponseData(response, rawResponse);    
    }
    
    
    public static AuthorizeResponseData getAuthorizeData(HttpResponseObject rawResponse) throws Exception {
        AuthorizeResponse response = marshalXML(AuthorizeResponse.class , rawResponse);
        return new AuthorizeResponseData(response, rawResponse);    
    }
    
    public static GetAuthorizationDetailsResponseData getAuthorizationDetailsData(HttpResponseObject rawResponse) throws Exception{
        GetAuthorizationDetailsResponse response = marshalXML(GetAuthorizationDetailsResponse.class , rawResponse);
        return new GetAuthorizationDetailsResponseData(response, rawResponse);
    }
    
    public static CaptureResponseData getCapture(HttpResponseObject rawResponse) throws Exception{
        CaptureResponse response = marshalXML(CaptureResponse.class , rawResponse);
        return new CaptureResponseData(response, rawResponse);     
    }
    
    public static GetCaptureDetailsResponseData getCaptureDetailsData(HttpResponseObject rawResponse) throws Exception {
        GetCaptureDetailsResponse response = marshalXML(GetCaptureDetailsResponse.class , rawResponse);
        return new GetCaptureDetailsResponseData(response, rawResponse);    
    }
    
    public static ConfirmOrderReferenceResponseData confirmOrderReference(HttpResponseObject rawResponse) throws Exception {
        ConfirmOrderReferenceResponse response = marshalXML(ConfirmOrderReferenceResponse.class , rawResponse);
        return new ConfirmOrderReferenceResponseData(response, rawResponse);
    }
    
    public static CloseAuthorizationResponseData closeAuthorizationResponse(HttpResponseObject rawResponse) throws Exception{
        CloseAuthorizationResponse response = marshalXML(CloseAuthorizationResponse.class, rawResponse);
        return new CloseAuthorizationResponseData(response, rawResponse);
    }
    
    public static CancelOrderReferenceResponseData getCancelOrderReference(HttpResponseObject rawResponse) throws Exception{
        CancelOrderReferenceResponse response = marshalXML(CancelOrderReferenceResponse.class, rawResponse);
        return new CancelOrderReferenceResponseData(response , rawResponse);
    }
    
    public static CloseOrderReferenceResponseData getCloseOrderReference(HttpResponseObject rawResponse) throws Exception {
        CloseOrderReferenceResponse response = marshalXML(CloseOrderReferenceResponse.class, rawResponse);
        return new CloseOrderReferenceResponseData(response, rawResponse);
    }
    
    public static RefundResponseData getRefundData(HttpResponseObject rawResponse) throws Exception {
        RefundResponse response = marshalXML(RefundResponse.class, rawResponse);
        return new RefundResponseData(response, rawResponse);
    }
    
    public static GetRefundDetailsResponseData getRefundDetailsData(HttpResponseObject rawResponse) throws Exception{
        GetRefundDetailsResponse response = marshalXML(GetRefundDetailsResponse.class, rawResponse);
        return new GetRefundDetailsResponseData(response, rawResponse);
    }
    
    public static GetBillingAgreementDetailsResponseData getBillingAgreementDetailsData(HttpResponseObject rawResponse ) throws Exception {
        GetBillingAgreementDetailsResponse response = marshalXML(GetBillingAgreementDetailsResponse.class, rawResponse);
        return new GetBillingAgreementDetailsResponseData(response , rawResponse);
    }
 
    public static SetBillingAgreementDetailsResponseData getSetBillingAgreementDetailsResponse(HttpResponseObject rawResponse ) throws Exception{
        SetBillingAgreementDetailsResponse response = marshalXML(SetBillingAgreementDetailsResponse.class, rawResponse);
        return new SetBillingAgreementDetailsResponseData(response , rawResponse);    
    }
    
    public static ValidateBillingAgreementResponseData getValidateBillingAgreementResponse(HttpResponseObject rawResponse ) throws Exception {
        ValidateBillingAgreementResponse response = marshalXML(ValidateBillingAgreementResponse.class, rawResponse);
        return new ValidateBillingAgreementResponseData(response , rawResponse);  
    }
    
    public static ConfirmBillingAgreementResponseData confirmBillingAgreementResponse( HttpResponseObject rawResponse ) throws Exception {
        ConfirmBillingAgreementResponse response = marshalXML(ConfirmBillingAgreementResponse.class, rawResponse);
        return new ConfirmBillingAgreementResponseData(response, rawResponse);  
    }
    
    public static AuthorizeOnBillingAgreementResponseData getAuthorizeOnBillingAgreement(HttpResponseObject rawResponse ) throws Exception {
        AuthorizeOnBillingAgreementResponse response = marshalXML(AuthorizeOnBillingAgreementResponse.class, rawResponse);
        return new AuthorizeOnBillingAgreementResponseData(response , rawResponse);
    }
    
    public static CloseBillingAgreementResponseData closeBillingAgreementResponse(HttpResponseObject rawResponse ) throws Exception{
        CloseBillingAgreementResponse response = marshalXML(CloseBillingAgreementResponse.class, rawResponse);
        return new CloseBillingAgreementResponseData(response , rawResponse);
    }
    
    public static GetProviderCreditDetailsResponseData getGetProviderCreditDetails( HttpResponseObject rawResponse ) throws Exception{
        GetProviderCreditDetailsResponse response = marshalXML(GetProviderCreditDetailsResponse.class, rawResponse);
        return new GetProviderCreditDetailsResponseData(response , rawResponse);    
    }
    
    public static GetProviderCreditReversalDetailsResponseData getProviderCreditReversalDetails( HttpResponseObject rawResponse ) throws Exception{
        GetProviderCreditReversalDetailsResponse response = marshalXML(GetProviderCreditReversalDetailsResponse.class, rawResponse);
        return new GetProviderCreditReversalDetailsResponseData(response , rawResponse);
    }
    
    public static ReverseProviderCreditResponseData getReverseProviderCreditResponseData(HttpResponseObject rawResponse ) throws Exception {
        ReverseProviderCreditResponse response = marshalXML(ReverseProviderCreditResponse.class, rawResponse);
        return new ReverseProviderCreditResponseData(response , rawResponse);
    }

    public static <T> T marshalXML(Class<T> clazz, HttpResponseObject rawReponse) throws AmazonServiceException  {
        try { 
        if (rawReponse.getStatusCode() == 200) {
            T responseObject = null;
            JAXBContext context = JAXBContext.newInstance(clazz);
            Unmarshaller jaxbUnmarshaller = context.createUnmarshaller();
            InputStream is = new ByteArrayInputStream(rawReponse.getData().getBytes());
            responseObject = clazz.cast(jaxbUnmarshaller.unmarshal(is));
            return responseObject;
        } else {
            generateErrorException(rawReponse);
        }
        } catch(JAXBException e) {
            //Log.error();
            throw new AmazonClientException("Encountered marshalling error in: " + rawReponse.getData() , e);
        }
    
    return null;
}
    
    public static void generateErrorException(HttpResponseObject rawResponse) throws AmazonServiceException, JAXBException {
        JAXBContext context = JAXBContext.newInstance(ErrorResponse.class);
        Unmarshaller jaxbUnmarshaller = context.createUnmarshaller();
        InputStream is = new ByteArrayInputStream(rawResponse.getData().getBytes());
        ErrorResponse result = (ErrorResponse) jaxbUnmarshaller.unmarshal(is);
        throw new AmazonServiceException(result , rawResponse );
    }
}
