package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.response.autogenerated.model.AuthorizationDetails;
import com.amazon.payments.lpa.response.autogenerated.model.RefundDetails;
import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;
import com.amazon.payments.lpa.response.autogenerated.model.RefundResponse;

public class RefundResponseData {
    
    private String rawXML;
    private String requestId;
    private RefundDetails refundDetails;
    
    public RefundResponseData(RefundResponse refundResponse , HttpResponseObject rawResponse) {
        this.rawXML = rawResponse.getData();
        if(refundResponse != null) {
            if(refundResponse.getRefundResult() != null) {
                refundDetails = refundResponse.getRefundResult().getRefundDetails();
            }
            this.requestId = refundResponse.getResponseMetadata().getRequestId();
        }
    }

    public String toXML() {
        return rawXML;
    }

    public String getRequestId() {
        return requestId;
    }

    public RefundDetails getDetails() {
        return refundDetails;
    }

}
