package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;
import com.amazon.payments.lpa.response.autogenerated.model.ProviderCreditReversalDetails;
import com.amazon.payments.lpa.response.autogenerated.model.ReverseProviderCreditResponse;

public class ReverseProviderCreditResponseData {
    
    private String rawXML;
    private String requestId;
    private ProviderCreditReversalDetails providerCreditReversalDetails;
    
    public ReverseProviderCreditResponseData(ReverseProviderCreditResponse reverseProviderCreditResponse , HttpResponseObject rawResponse) {
        this.rawXML = rawResponse.getData();
        if(reverseProviderCreditResponse != null) {
            if(reverseProviderCreditResponse.getReverseProviderCreditResult()!= null) {
                this.providerCreditReversalDetails = reverseProviderCreditResponse.getReverseProviderCreditResult().getProviderCreditReversalDetails();
            }
            this.requestId = reverseProviderCreditResponse.getResponseMetadata().getRequestId();
        }
    }

    public String toXML() {
        return rawXML;
    }

    public String getRequestId() {
        return requestId;
    }

    public ProviderCreditReversalDetails getDetails() {
        return providerCreditReversalDetails;
    }
}
