package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.response.autogenerated.model.BillingAgreementDetails;
import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;
import com.amazon.payments.lpa.response.autogenerated.model.SetBillingAgreementDetailsResponse;


public class SetBillingAgreementDetailsResponseData {
    
    private String rawXML;
    private String requestId;
    private BillingAgreementDetails billingAgreementDetails;
    
    public SetBillingAgreementDetailsResponseData(SetBillingAgreementDetailsResponse response , HttpResponseObject rawResponse) {
        this.rawXML = rawResponse.getData();
        if(response != null) {
            this.requestId = response.getResponseMetadata().getRequestId();
            if(response.getSetBillingAgreementDetailsResult() != null) { 
               billingAgreementDetails = response.getSetBillingAgreementDetailsResult().getBillingAgreementDetails();
            }
        }
    }

    public String toXML() {
        return rawXML;
    }

    public String getRequestId() {
        return requestId;
    }

    public BillingAgreementDetails getDetails() {
        return billingAgreementDetails;
    }
    
    
    

}
