package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.response.autogenerated.model.SetOrderReferenceDetailsResponse;
import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;
import com.amazon.payments.lpa.response.autogenerated.model.OrderReferenceDetails;


public class SetOrderReferenceDetailsResponseData {
    
    private String xml;
    private String requestId;
    private OrderReferenceDetails orderDetails;
    
    public SetOrderReferenceDetailsResponseData(SetOrderReferenceDetailsResponse response , HttpResponseObject rawResponse) {
        this.xml = rawResponse.getData();
        if(response != null) {
            this.requestId = response.getResponseMetadata().getRequestId();
            if(response.getSetOrderReferenceDetailsResult() != null) { 
               orderDetails = response.getSetOrderReferenceDetailsResult().getOrderReferenceDetails();
            }
        }
    }

    public String toXML() {
        return xml;
    }

    public String getRequestId() {
        return requestId;
    }

    public OrderReferenceDetails getDetails() {
        return orderDetails;
    }
    
    
    

}
