package com.amazon.payments.lpa.response.parser;

import com.amazon.payments.lpa.response.autogenerated.model.HttpResponseObject;
import com.amazon.payments.lpa.response.autogenerated.model.ValidateBillingAgreementResponse;

public class ValidateBillingAgreementResponseData {
    
    private String responseXML;
    private String requestId;
    
    public ValidateBillingAgreementResponseData(ValidateBillingAgreementResponse validateBillingAgreementResponse , HttpResponseObject rawResponse) {
        this.responseXML = rawResponse.getData();
        if(validateBillingAgreementResponse != null) {
            if(validateBillingAgreementResponse.getResponseMetadata() != null) {
                this.requestId = validateBillingAgreementResponse.getResponseMetadata().getRequestId();
            }
        }
    }

    public String toXML() {
        return responseXML;
    }

    public String getRequestId() {
        return requestId;
    }
    
}
