package com.amazonservices.mws.offamazonpayments.utilities;

import com.google.common.base.CaseFormat;

public enum Operation {
    AUTHORIZE_ON_BILLING_AGREEMENT,
    AUTHORIZE,
    CANCEL_ORDER_REFERENCE,
    CAPTURE,
    CLOSE_AUTHORIZATION,
    CLOSE_BILLING_AGREEMENT,
    CLOSE_ORDER_REFERENCE,
    CONFIRM_BILLING_AGREEMENT,
    CONFIRM_ORDER_REFERENCE,
    CREATE_ORDER_REFERENCE_FOR_ID,
    GET_AUTHORIZATION_DETAILS,
    GET_BILLING_AGREEMENT_DETAILS,
    GET_CAPTURE_DETAILS,
    GET_ORDER_REFERENCE_DETAILS,
    GET_PROVIDER_CREDIT_DETAILS,
    GET_PROVIDER_CREDIT_REVERSAL_DETAILS,
    GET_REFUND_DETAILS,
    REVERSE_PROVIDER_CREDIT,
    REFUND,
    SET_BILLING_AGREEMENT_DETAILS,
    SET_ORDER_REFERENCE_DETAILS,
    VALIDATE_BILLING_AGREEMENT;

    @Override
    public String toString() {
        return CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.UPPER_CAMEL, this.name());
    }
}
