package com.amazon.payments.paywithamazon;

import com.amazon.payments.paywithamazon.impl.PaymentsConfig;
import com.amazon.payments.paywithamazon.response.autogenerated.model.Environment;
import com.amazon.payments.paywithamazon.types.CurrencyCode;
import com.amazon.payments.paywithamazon.types.Region;


public interface Config {

    /**
     * Returns MWS Access KeyID from client configuration
     * @return accessKeyId
     */
    String getAccessKeyId();

    /**
     * Returns the application name from client configuration
     * @return applicationName
     *
     */
    String getApplicationName();

    /**
     * Returns the application version set in the client configuration
     * @return applicationVersion
     *
     */
    String getApplicationVersion();

    /**
     * Returns currencyCode in PaymentsConfig
     * @see com.amazon.payments.lpa.types.CurrencyCode
     *
     * @return currencyCode
     */
    CurrencyCode getCurrencyCode();

    /**
     * Returns the environment from client configuration
     * @see com.amazon.payments.lpa.types.Environment
     * @return environment
     *
     */
    Environment getEnvironment();

    /**
     * Returns the proxy host set in the client configuration
     * @return proxyHost
     */
    String getProxyHost();

    /**
     * Returns proxy password in PaymentsConfig
     *
     * @return proxyPassword
     */
    String getProxyPassword();
    /**
     * Sets proxy username in configuration.
     * @param proxyPassword
     *
     * @return
     *          Returns updated PaymentsConfig object
     */

    /**
     * Returns proxy port from PaymentsConfig
     * @return proxyPort
     *
     */
    int getProxyPort();

    /**
     * Returns proxy username from PaymentsConfig
     * @return proxyUsername
     */
    String getProxyUsername();

    /**
     * Returns region code from client configuration
     * @see com.amazon.payments.lpa.types.Region
     * @return region
     */
    Region getRegion();

    /**
     * Returns MWS Secret Access Key from client configuration
     * @return secretAccessKey
     *
     */
    String getSecretAccessKey();

    /**
     * Returns the merchantId or sellerId from client configuration
     * @return sellerId
     *
     */
    String getSellerId();

    /**
     * Returns true if Client retries on service exceptions that are either 500 internal server
     * errors, 503 service unavailable errors, service throttling errors.
     */
    boolean isUseAutoRetryOnThrottle();

    /**
     *  If true, sets environment to SANDBOX mode.
     *  All Login And Pay with Amazon API operations will be done in Sandbox Mode.
     *  {@link com.amazon.payments.lpa.types.Environment Environment}.
     *
     * @param isSandbox
     *
     * @return updated PaymentsConfig container
     */
    PaymentsConfig sandboxMode(boolean isSandbox);

    /**
     * Sets AccessKey in PaymentsConfig
     * @param accessKeyId
     */
    void setAccessKeyId(String accessKeyId);

    /**
     * Sets Application Name in PaymentsConfig
     * @param applicationName
     */
    void setApplicationName(String applicationName);

    /**
     * Sets Application Version in PaymentsConfig
     * @param applicationVersion
     */
    void setApplicationVersion(String applicationVersion);

    /**
     * Sets currencyCode in PaymentsConfig
     * @see com.amazon.payments.lpa.types.CurrencyCode
     * @param currencyCode
     */
    void setCurrencyCode(CurrencyCode currencyCode);

    /**
     * Sets Environment in PaymentsConfig
     * @see com.amazon.payments.lpa.types.Environment
     *
     * @param environment
     */
    void setEnvironment(Environment environment);

    /**
     * Sets proxy host in PaymentsConfig
     * @param proxyHost
     */
    void setProxyHost(String proxyHost);

    /**
     * Set proxy password in PaymentsConfig
     * @param proxyPassword
     */
    void setProxyPassword(String proxyPassword);

    /**
     * Sets proxy port in PaymentsConfig
     * @param proxyPort
     */
    void setProxyPort(int proxyPort);

    /**
     * Sets proxy username in PaymentsConfig
     * @param proxyUsername
     */
    void setProxyUsername(String proxyUsername);

    /**
     * Identifies region associated with Login And Pay with Amazon API operations.
     *                  {@link com.amazon.payments.lpa.types.Region Region}.
     *
     * @param region
     *
     */
    void setRegion(Region region);

    /**
     * Sets SecretKey in PaymentsConfig
     * @param secretAccessKey
     */
    void setSecretAccessKey(String secretAccessKey);

    /**
     * Sets SellerId in PaymentsConfig
     * @param sellerId
     */
    void setSellerId(String sellerId);

    /**
     * Sets autoRetryOnThrottle in PaymentsConfig
     * If set to true, client will retry on service exceptions that are either 500 internal server
     * errors, 503 service unavailable errors, service throttling errors.
     *
     * @param useAutoRetryOnThrottle
     */
    void setUseAutoRetryOnThrottle(boolean useAutoRetryOnThrottle);

    /**
     * The string representation of configuration parameters
     *
     * @return Returns the string representation of configuration parameters
     */
    String toString();

    /**
     * Optional parameter. This method sets application name in
     *                  client configuration.
     * @param applicationName
     * @return
     *          Returns updated ClientConfig object
     */
    PaymentsConfig withApplicationName(String applicationName);

    /**
     * Optional parameter. This method sets application version in client configuration.
     * @param applicationVersion
     *
     * @return Returns updated ClientConfig object
     */
    PaymentsConfig withApplicationVersion(String applicationVersion);

    /**
     * Represents currency code to be used for all Login And Pay with Amazon API operations.
     *                  Accepts three-digit currency code. In ISO 4217 format.
     *                  {@link com.amazon.payments.lpa.types.CurrencyCode CurrencyCode}
     *
     * @param currencyCode
     *
     * @return Returns the updated PaymentsConfig container
     */
    PaymentsConfig withCurrencyCode(CurrencyCode currencyCode);

    /**
     *  Identifies environment(i.e. LIVE or SANDBOX mode) associated with Login And Pay with Amazon API operations.
     *  {@link com.amazon.payments.lpa.types.Environment Environment}.
     *
     * @param environment
     *
     * @return updated PaymentsConfig container
     */
    PaymentsConfig withEnvironment(Environment environment);

    /**
     * Optional parameter. This method sets proxy host in client configuration
     * @param proxyHost
     * @return Returns updated ClientConfig object
     */
    PaymentsConfig withProxyHost(String proxyHost);

    PaymentsConfig withProxyPassword(String proxyPassword);

    /**
     * Optional parameter. This method sets proxy port in PaymentsConfig
     * @param proxyPort
     * @return Returns updated PaymentsConfig object
     */
    PaymentsConfig withProxyPort(int proxyPort);

    /**
     * Optional parameter. This methods sets proxy username in PaymentsConfig
     * @param proxyUsername
     * @return Returns updated ClientConfig object
     */
    PaymentsConfig withProxyUsername(String proxyUsername);

    /**
     * Identifies region associated with Login And Pay with Amazon API operations.
     *                  {@link com.amazon.payments.lpa.types.Region Region}.
     *
     * @param region
     *
     * @return updated PaymentsConfig container
     *
     */
    PaymentsConfig withRegion(Region region);

    /**
     * Sets autoRetryOnThrottle in PaymentsConfig
     * If set to true, client will retry on service exceptions that are either 500 internal server
     * errors, 503 service unavailable errors, service throttling errors.
     *
     * @return PaymentsConfig
     */
    PaymentsConfig withUseAutoRetryOnThrottle(boolean useAutoRetryOnThrottle);
    
}
