package com.amazon.payments.paywithamazon.response.ipn.model;

/**
 * Notification types generated by the Off Amazon 
 * Payments Notification service
 */
public enum NotificationType {
    OrderReferenceNotification,
    AuthorizationNotification,
    CaptureNotification,
    RefundNotification,
    BillingAgreementNotification,
    ProviderCreditNotification,
    ProviderCreditReversalNotification,
    SolutionProviderMerchantNotification
}

