package com.amazon.payments.paywithamazon.response.autogenerated.ipn;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * An IPN notification to indicate a change in status for
 * a solutionProviderMerchant transaction notification.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "merchantRegistrationDetails" })
@XmlRootElement(name = "SolutionProviderMerchantNotification")
public class SolutionProviderMerchantNotification  extends Notification {

    @XmlElement(name = "MerchantRegistrationDetails", required = true)
    private MerchantRegistrationDetails merchantRegistrationDetails;

    public SolutionProviderMerchantNotification() {
        super(NotificationType.SolutionProviderMerchantNotification);
    }

    public SolutionProviderMerchantNotification(final MerchantRegistrationDetails details) {
        super(NotificationType.SolutionProviderMerchantNotification);
        merchantRegistrationDetails = details;
    }

    public MerchantRegistrationDetails getMerchantRegistrationDetails() {
        return this.merchantRegistrationDetails;
    }

}
